### ISSUE TITLE
Manufacturer contacts needed

### ISSUE THREAD

**Issue by AndrewOG255** [lmesserStep/LibreSDRB210#2]
I am representing a European company considering purchasing this board in significant quantities with some customizations. Could you please provide the manufacturer's contact information?
![LibreSDR_B210](https://github.com/user-attachments/assets/c5f271b6-db53-4d2d-8692-a148ee57a10b)

**Comment by lmesserStep** [comment]
I am unable to provide the manufacture contact information.
